name: GitHub Actions
run-name: Restart discord bot server to pull new commit(s) on push action
on:
  push:
    branches:
      - master
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          PTE_PANEL_URL: ${{ secrets.PTE_PANEL_URL }}
          PTE_BEARER_TOKEN: ${{ secrets.PTE_BEARER_TOKEN }}
          PTE_PANEL_ID: ${{ secrets.PTE_PANEL_ID }}